# Generated by Django 2.2.4 on 2019-11-25 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('bill_id', models.AutoField(primary_key=True, serialize=False)),
                ('bill_date', models.DateField(auto_now_add=True)),
                ('bill_clint_name', models.CharField(max_length=250)),
                ('bill_product_pcs', models.IntegerField(default=0)),
                ('total_price', models.IntegerField(default=0)),
                ('bill_paid', models.IntegerField(default=0)),
                ('bill_unpaid', models.IntegerField(default=0)),
                ('bill_temp', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Clint',
            fields=[
                ('clint_id', models.AutoField(primary_key=True, serialize=False)),
                ('clint_name', models.CharField(max_length=250)),
                ('clint_piece', models.IntegerField()),
                ('clint_pmoney', models.IntegerField()),
                ('clint_umoney', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employee_id', models.AutoField(primary_key=True, serialize=False)),
                ('employee_name', models.CharField(max_length=250)),
                ('employee_address', models.CharField(max_length=250)),
                ('employee_number', models.CharField(max_length=10)),
            ],
        ),
    ]
