# Generated by Django 2.2.4 on 2019-11-26 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0002_remove_bill_bill_temp'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='bill_phone_number',
            field=models.IntegerField(default=0),
        ),
    ]
