# Generated by Django 2.2.4 on 2019-11-26 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0003_bill_bill_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='bill_phone_number',
            field=models.CharField(max_length=10),
        ),
    ]
