# Generated by Django 2.2.4 on 2019-11-26 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0004_auto_20191126_1651'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='bill_phone_number',
        ),
    ]
