# Generated by Django 2.2.4 on 2019-11-26 11:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0005_remove_bill_bill_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='bill_mobile_number',
            field=models.CharField(default=django.utils.timezone.now, max_length=10),
            preserve_default=False,
        ),
    ]
