# Generated by Django 2.2.4 on 2019-12-08 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0006_bill_bill_mobile_number'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Clint',
        ),
    ]
