# Generated by Django 2.2.4 on 2019-12-08 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0007_delete_clint'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clint',
            fields=[
                ('clint_id', models.AutoField(primary_key=True, serialize=False)),
                ('clint_name', models.CharField(max_length=50)),
                ('clint_add', models.TextField(max_length=500)),
                ('clint_mobile', models.CharField(max_length=10)),
            ],
        ),
    ]
